service: users

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: ${opt:stage}
  deploymentBucket:
    name: boristane-lambdas-deployments
  region: eu-west-2
  logRetentionInDays: 7
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${file(./${opt:stage}.yml):snsTopicArn}

  environment:
    ENV: ${opt:stage}
    DB_HOST: ${file(./${opt:stage}.yml):dbHost}
    DB_USER: ${file(./${opt:stage}.yml):dbUser}
    DB_PASS: ${ssm:/boristane/lesley/database/password~true}
    DB_PORT: ${file(./${opt:stage}.yml):dbPort}
    DB_NAME: ${file(./${opt:stage}.yml):dbName}
    JWT_USERS_KEY: ${file(./${opt:stage}.yml):jwtUsersKey}
    JWT_ADMINS_KEY: ${file(./${opt:stage}.yml):jwtAdminsKey}
    SNS_TOPIC_ARN: ${file(./${opt:stage}.yml):snsTopicArn}
    SNS_REGION: ${file(./${opt:stage}.yml):snsRegion}
    FORGOTTEN_PASSWORD_URL: ${file(./${opt:stage}.yml):forgottenPasswordUrl}

functions:
  server:
    handler: .build/serverless.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'